//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vrc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vrc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced audio cannot be activated because your version of Vietcong Remastered does not contain the necessary files. Please update to the latest version..
        /// </summary>
        internal static string AudioError1 {
            get {
                return ResourceManager.GetString("AudioError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings for the enhanced sounds could not be saved: {0}.
        /// </summary>
        internal static string AudioErrorGeneric {
            get {
                return ResourceManager.GetString("AudioErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cc894e4b_cac2_4ff2_8327_4b787907d956 {
            get {
                object obj = ResourceManager.GetObject("cc894e4b_cac2_4ff2_8327_4b787907d956", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable improved weapon sounds.
        /// </summary>
        internal static string DisableImprovedWeaponsSound {
            get {
                return ResourceManager.GetString("DisableImprovedWeaponsSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable translucent vegetation.
        /// </summary>
        internal static string DisableTranslucentVegetation {
            get {
                return ResourceManager.GetString("DisableTranslucentVegetation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        internal static string Extreme {
            get {
                return ResourceManager.GetString("Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fist Alpha DLC.
        /// </summary>
        internal static string FistAlpha {
            get {
                return ResourceManager.GetString("FistAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontItalics {
            get {
                object obj = ResourceManager.GetObject("fontItalics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force V-Sync.
        /// </summary>
        internal static string ForceVSync {
            get {
                return ResourceManager.GetString("ForceVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help cannot be displayed because the navod.pdf file is missing.
        /// </summary>
        internal static string HelpError {
            get {
                return ResourceManager.GetString("HelpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved 3D Sound.
        /// </summary>
        internal static string Improved3dSound {
            get {
                return ResourceManager.GetString("Improved3dSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postprocessing quality.
        /// </summary>
        internal static string PostprocessingQuality {
            get {
                return ResourceManager.GetString("PostprocessingQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings of the rated game could not be saved because the file /files/ranked/4.cbf does not exist.
        /// </summary>
        internal static string RankedError1 {
            get {
                return ResourceManager.GetString("RankedError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings of the rated game could not be saved because the file /files/entra/4.cbf does not exist.
        /// </summary>
        internal static string RankedError2 {
            get {
                return ResourceManager.GetString("RankedError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings of the rated game could not be saved: {0}.
        /// </summary>
        internal static string RankedErrorgeneric {
            get {
                return ResourceManager.GetString("RankedErrorgeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked multiplayer mode.
        /// </summary>
        internal static string RankedMode {
            get {
                return ResourceManager.GetString("RankedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietcong Remastered contains a ReShade.ini file that was not found. Place vietcong_remastered.exe in the folder containing vietcong.exe and ReShade.ini.
        /// </summary>
        internal static string ReShadeError1 {
            get {
                return ResourceManager.GetString("ReShadeError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Vietcong Remastered Launcher in the folder where vietcong.exe is located.
        /// </summary>
        internal static string ReShadeError2 {
            get {
                return ResourceManager.GetString("ReShadeError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while parsing ReShade.ini: {0}.
        /// </summary>
        internal static string ReShadeErrorGeneric {
            get {
                return ResourceManager.GetString("ReShadeErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings could not be saved, ReShade.ini does not exist.
        /// </summary>
        internal static string SettingsError1 {
            get {
                return ResourceManager.GetString("SettingsError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings could not be saved: {0}.
        /// </summary>
        internal static string SettingsErrorGeneric {
            get {
                return ResourceManager.GetString("SettingsErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show FPS.
        /// </summary>
        internal static string ShowFps {
            get {
                return ResourceManager.GetString("ShowFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing with the game configuration, a moment of patience....
        /// </summary>
        internal static string UiSynchronizing {
            get {
                return ResourceManager.GetString("UiSynchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra.
        /// </summary>
        internal static string Ultra {
            get {
                return ResourceManager.GetString("Ultra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra Low.
        /// </summary>
        internal static string UltraLow {
            get {
                return ResourceManager.GetString("UltraLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced vegetation settings could not be saved because the /files/entra/4.cbf file does not exist.
        /// </summary>
        internal static string VegetationError1 {
            get {
                return ResourceManager.GetString("VegetationError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced vegetation settings could not be saved because the /files/distra/4.cbf file does not exist.
        /// </summary>
        internal static string VegetationError2 {
            get {
                return ResourceManager.GetString("VegetationError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced vegetation settings could not be saved: {0}.
        /// </summary>
        internal static string VegetationErrorGeneric {
            get {
                return ResourceManager.GetString("VegetationErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        internal static string VeryHigh {
            get {
                return ResourceManager.GetString("VeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietcong Classic.
        /// </summary>
        internal static string VietcongClassic {
            get {
                return ResourceManager.GetString("VietcongClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game cannot be started because the vietcong.exe file does not exist.
        /// </summary>
        internal static string VietcongExeMissing {
            get {
                return ResourceManager.GetString("VietcongExeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced weapon sound settings could not be saved because there is no /files/disso/3.cbf file.
        /// </summary>
        internal static string WeaponsAudioError1 {
            get {
                return ResourceManager.GetString("WeaponsAudioError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings for the enhanced weapon sounds could not be saved because the /files/enso/3.cbf file does not exist.
        /// </summary>
        internal static string WeaponsAudioError2 {
            get {
                return ResourceManager.GetString("WeaponsAudioError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings for the enhanced weapon sounds could not be saved: {0}.
        /// </summary>
        internal static string WeaponsAudioErrorGeneric {
            get {
                return ResourceManager.GetString("WeaponsAudioErrorGeneric", resourceCulture);
            }
        }
    }
}
